name: Build and Package

on:
  push:
    branches:
      - '**'
  pull_request:
    # branches: [ master ]
  workflow_dispatch:

jobs:
  build_linux_apk:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3
      id: setup
    
    - name: Build
      uses: docker/build-push-action@v6
      with:
        push: false
        platforms: linux/arm/v7
        # do not cache layers
        file: Dockerfile
        outputs: type=local,dest=dist
        provenance: false
        context: .
  

